// This file is auto-generated by @hey-api/openapi-ts

export type ClientOptions = {
    baseUrl: 'http://localhost:8080' | (string & {});
};

export type ImportConfigRequest = {
    /**
     * Optional seed/export date string.
     */
    date?: string;
    title: string;
    /**
     * Display column count kept as string for legacy config compatibility.
     */
    columns: string;
    items: Array<ConfigCategory>;
};

export type ExportConfigResponse = {
    /**
     * Optional seed/export date string.
     */
    date?: string;
    title: string;
    /**
     * Display column count kept as string for legacy config compatibility.
     */
    columns: string;
    items: Array<ConfigCategory>;
};

export type Pagination = {
    limit: number;
    offset: number;
    total: number;
    hasMore: boolean;
};

export type CategoryListResponse = {
    data: Array<Category>;
    pagination: Pagination;
};

export type ServiceListResponse = {
    data: Array<Service>;
    pagination: Pagination;
};

export type AuditLogListResponse = {
    data: Array<AuditLog>;
    pagination: Pagination;
};

export type ConfigCategory = {
    name: string;
    icon: string;
    list: Array<ConfigService>;
};

export type ConfigService = {
    name: string;
    logo: string;
    url: string;
    target: '_blank' | '_self';
    monitorUrl?: string;
    monitorEnabled?: boolean;
};

export type DashboardSettings = {
    /**
     * Optional seed/export date string.
     */
    date?: string;
    title: string;
    columns: number;
};

export type Category = {
    /**
     * Stable category id used by v1 resource endpoints.
     */
    id: number;
    name: string;
    /**
     * Font Awesome class string, for example fa-solid fa-folder.
     */
    icon: string;
    order: number;
    services?: Array<Service>;
};

export type Service = {
    /**
     * Stable service id used by v1 resource endpoints.
     */
    id: number;
    /**
     * Parent category id used by v1 resource endpoints.
     */
    categoryId: number;
    name: string;
    /**
     * Local asset path, remote image URL, or empty for automatic favicon discovery.
     */
    logo?: string;
    url: string;
    target: '_blank' | '_self';
    /**
     * Optional URL used for health checks. Defaults to url when omitted.
     */
    monitorUrl?: string;
    monitorEnabled: boolean;
    order: number;
};

export type ServiceStatus = {
    name: string;
    status: 'up' | 'down';
    method?: 'HEAD' | 'GET';
    code: number;
    responseTimeMs: number;
    checkedAt: string;
    error?: string;
};

export type AuditLog = {
    id: number;
    actorType: string;
    actorId?: string;
    actorName?: string;
    action: string;
    resourceType: string;
    resourceId?: string;
    summary: string;
    /**
     * JSON snapshot before the successful operation.
     */
    before?: {
        [key: string]: unknown;
    };
    /**
     * JSON snapshot after the successful operation.
     */
    after?: {
        [key: string]: unknown;
    };
    metadata?: {
        [key: string]: unknown;
    };
    requestId?: string;
    ipAddress?: string;
    userAgent?: string;
    createdAt: string;
};

export type ApiError = {
    code: string;
    message: string;
    fields?: Array<ValidationErrorField>;
};

export type ValidationErrorField = {
    field: string;
    message: string;
};

export type CategoryCreateRequest = {
    name: string;
    icon: string;
};

export type CategoryUpdateRequest = {
    name?: string;
    icon?: string;
    order?: number;
};

export type ServiceCreateRequest = {
    categoryId: number;
    name: string;
    logo?: string;
    url: string;
    target: '_blank' | '_self';
    monitorUrl?: string;
    monitorEnabled?: boolean;
};

export type ServiceUpdateRequest = {
    categoryId?: number;
    order?: number;
    name?: string;
    logo?: string;
    url?: string;
    target?: '_blank' | '_self';
    monitorUrl?: string;
    monitorEnabled?: boolean;
};

/**
 * Category identifier.
 */
export type CategoryId = number;

/**
 * Optional category filter.
 */
export type CategoryIdQuery = number;

/**
 * Maximum number of records to return. Defaults to 100 for categories/services and 50 for audit logs.
 */
export type LimitParam = number;

/**
 * Number of records to skip before returning the page.
 */
export type OffsetParam = number;

/**
 * Service identifier.
 */
export type ServiceId = number;

export type GetDashboardData = {
    body?: never;
    path?: never;
    query?: never;
    url: '/api/v1/dashboard';
};

export type GetDashboardErrors = {
    /**
     * Unexpected server error
     */
    500: ApiError;
};

export type GetDashboardError = GetDashboardErrors[keyof GetDashboardErrors];

export type GetDashboardResponses = {
    /**
     * Dashboard settings
     */
    200: DashboardSettings;
};

export type GetDashboardResponse = GetDashboardResponses[keyof GetDashboardResponses];

export type ExportConfigData = {
    body?: never;
    path?: never;
    query?: never;
    url: '/api/v1/export';
};

export type ExportConfigErrors = {
    /**
     * Unexpected server error
     */
    500: ApiError;
};

export type ExportConfigError = ExportConfigErrors[keyof ExportConfigErrors];

export type ExportConfigResponses = {
    /**
     * Current dashboard config in legacy-compatible import/export shape
     */
    200: ExportConfigResponse;
};

export type ExportConfigResponse2 = ExportConfigResponses[keyof ExportConfigResponses];

export type ImportConfigData = {
    body: ImportConfigRequest;
    path?: never;
    query?: never;
    url: '/api/v1/import';
};

export type ImportConfigErrors = {
    /**
     * Malformed JSON or invalid request/query syntax
     */
    400: ApiError;
    /**
     * HTTP method is not allowed for this resource
     */
    405: ApiError;
    /**
     * Unexpected server error
     */
    500: ApiError;
};

export type ImportConfigError = ImportConfigErrors[keyof ImportConfigErrors];

export type ImportConfigResponses = {
    /**
     * Imported dashboard config
     */
    200: ExportConfigResponse;
};

export type ImportConfigResponse = ImportConfigResponses[keyof ImportConfigResponses];

export type ListCategoriesData = {
    body?: never;
    path?: never;
    query?: {
        /**
         * Maximum number of records to return. Defaults to 100 for categories/services and 50 for audit logs.
         */
        limit?: number;
        /**
         * Number of records to skip before returning the page.
         */
        offset?: number;
    };
    url: '/api/v1/categories';
};

export type ListCategoriesErrors = {
    /**
     * HTTP method is not allowed for this resource
     */
    405: ApiError;
    /**
     * Unexpected server error
     */
    500: ApiError;
};

export type ListCategoriesError = ListCategoriesErrors[keyof ListCategoriesErrors];

export type ListCategoriesResponses = {
    /**
     * Categories sorted by display order
     */
    200: CategoryListResponse;
};

export type ListCategoriesResponse = ListCategoriesResponses[keyof ListCategoriesResponses];

export type CreateCategoryData = {
    body: CategoryCreateRequest;
    path?: never;
    query?: never;
    url: '/api/v1/categories';
};

export type CreateCategoryErrors = {
    /**
     * Malformed JSON or invalid request/query syntax
     */
    400: ApiError;
    /**
     * HTTP method is not allowed for this resource
     */
    405: ApiError;
    /**
     * Request field validation failed
     */
    422: ApiError;
    /**
     * Unexpected server error
     */
    500: ApiError;
};

export type CreateCategoryError = CreateCategoryErrors[keyof CreateCategoryErrors];

export type CreateCategoryResponses = {
    /**
     * Created category
     */
    201: Category;
};

export type CreateCategoryResponse = CreateCategoryResponses[keyof CreateCategoryResponses];

export type DeleteCategoryData = {
    body?: never;
    path: {
        /**
         * Category identifier.
         */
        categoryId: number;
    };
    query?: never;
    url: '/api/v1/categories/{categoryId}';
};

export type DeleteCategoryErrors = {
    /**
     * Resource not found
     */
    404: ApiError;
    /**
     * HTTP method is not allowed for this resource
     */
    405: ApiError;
    /**
     * Unexpected server error
     */
    500: ApiError;
};

export type DeleteCategoryError = DeleteCategoryErrors[keyof DeleteCategoryErrors];

export type DeleteCategoryResponses = {
    /**
     * Category deleted
     */
    204: void;
};

export type DeleteCategoryResponse = DeleteCategoryResponses[keyof DeleteCategoryResponses];

export type UpdateCategoryData = {
    body: CategoryUpdateRequest;
    path: {
        /**
         * Category identifier.
         */
        categoryId: number;
    };
    query?: never;
    url: '/api/v1/categories/{categoryId}';
};

export type UpdateCategoryErrors = {
    /**
     * Malformed JSON or invalid request/query syntax
     */
    400: ApiError;
    /**
     * Resource not found
     */
    404: ApiError;
    /**
     * HTTP method is not allowed for this resource
     */
    405: ApiError;
    /**
     * Request field validation failed
     */
    422: ApiError;
    /**
     * Unexpected server error
     */
    500: ApiError;
};

export type UpdateCategoryError = UpdateCategoryErrors[keyof UpdateCategoryErrors];

export type UpdateCategoryResponses = {
    /**
     * Updated category
     */
    200: Category;
};

export type UpdateCategoryResponse = UpdateCategoryResponses[keyof UpdateCategoryResponses];

export type ListServicesData = {
    body?: never;
    path?: never;
    query?: {
        /**
         * Optional category filter.
         */
        categoryId?: number;
        /**
         * Maximum number of records to return. Defaults to 100 for categories/services and 50 for audit logs.
         */
        limit?: number;
        /**
         * Number of records to skip before returning the page.
         */
        offset?: number;
    };
    url: '/api/v1/services';
};

export type ListServicesErrors = {
    /**
     * Malformed JSON or invalid request/query syntax
     */
    400: ApiError;
    /**
     * HTTP method is not allowed for this resource
     */
    405: ApiError;
    /**
     * Unexpected server error
     */
    500: ApiError;
};

export type ListServicesError = ListServicesErrors[keyof ListServicesErrors];

export type ListServicesResponses = {
    /**
     * Services sorted by category and display order
     */
    200: ServiceListResponse;
};

export type ListServicesResponse = ListServicesResponses[keyof ListServicesResponses];

export type CreateServiceData = {
    body: ServiceCreateRequest;
    path?: never;
    query?: never;
    url: '/api/v1/services';
};

export type CreateServiceErrors = {
    /**
     * Malformed JSON or invalid request/query syntax
     */
    400: ApiError;
    /**
     * HTTP method is not allowed for this resource
     */
    405: ApiError;
    /**
     * Request field validation failed
     */
    422: ApiError;
    /**
     * Unexpected server error
     */
    500: ApiError;
};

export type CreateServiceError = CreateServiceErrors[keyof CreateServiceErrors];

export type CreateServiceResponses = {
    /**
     * Created service
     */
    201: Service;
};

export type CreateServiceResponse = CreateServiceResponses[keyof CreateServiceResponses];

export type DeleteServiceData = {
    body?: never;
    path: {
        /**
         * Service identifier.
         */
        serviceId: number;
    };
    query?: never;
    url: '/api/v1/services/{serviceId}';
};

export type DeleteServiceErrors = {
    /**
     * Resource not found
     */
    404: ApiError;
    /**
     * HTTP method is not allowed for this resource
     */
    405: ApiError;
    /**
     * Unexpected server error
     */
    500: ApiError;
};

export type DeleteServiceError = DeleteServiceErrors[keyof DeleteServiceErrors];

export type DeleteServiceResponses = {
    /**
     * Service deleted
     */
    204: void;
};

export type DeleteServiceResponse = DeleteServiceResponses[keyof DeleteServiceResponses];

export type UpdateServiceData = {
    body: ServiceUpdateRequest;
    path: {
        /**
         * Service identifier.
         */
        serviceId: number;
    };
    query?: never;
    url: '/api/v1/services/{serviceId}';
};

export type UpdateServiceErrors = {
    /**
     * Malformed JSON or invalid request/query syntax
     */
    400: ApiError;
    /**
     * Resource not found
     */
    404: ApiError;
    /**
     * HTTP method is not allowed for this resource
     */
    405: ApiError;
    /**
     * Request field validation failed
     */
    422: ApiError;
    /**
     * Unexpected server error
     */
    500: ApiError;
};

export type UpdateServiceError = UpdateServiceErrors[keyof UpdateServiceErrors];

export type UpdateServiceResponses = {
    /**
     * Updated service
     */
    200: Service;
};

export type UpdateServiceResponse = UpdateServiceResponses[keyof UpdateServiceResponses];

export type GetStatusData = {
    body?: never;
    path?: never;
    query?: never;
    url: '/api/v1/status';
};

export type GetStatusErrors = {
    /**
     * Unexpected server error
     */
    500: ApiError;
};

export type GetStatusError = GetStatusErrors[keyof GetStatusErrors];

export type GetStatusResponses = {
    /**
     * Current service status keyed by service id
     */
    200: {
        [key: string]: ServiceStatus;
    };
};

export type GetStatusResponse = GetStatusResponses[keyof GetStatusResponses];

export type ListAuditLogsData = {
    body?: never;
    path?: never;
    query?: {
        /**
         * Filter by action, for example service.update.
         */
        action?: string;
        /**
         * Filter by resource type.
         */
        resourceType?: string;
        /**
         * Filter by resource identifier.
         */
        resourceId?: string;
        /**
         * Maximum number of records to return. Defaults to 100 for categories/services and 50 for audit logs.
         */
        limit?: number;
        /**
         * Number of records to skip before returning the page.
         */
        offset?: number;
    };
    url: '/api/v1/audit-logs';
};

export type ListAuditLogsErrors = {
    /**
     * HTTP method is not allowed for this resource
     */
    405: ApiError;
    /**
     * Unexpected server error
     */
    500: ApiError;
};

export type ListAuditLogsError = ListAuditLogsErrors[keyof ListAuditLogsErrors];

export type ListAuditLogsResponses = {
    /**
     * Audit logs sorted by newest first. Defaults to limit 50 and offset 0.
     */
    200: AuditLogListResponse;
};

export type ListAuditLogsResponse = ListAuditLogsResponses[keyof ListAuditLogsResponses];

export type StreamStatusData = {
    body?: never;
    path?: never;
    query?: never;
    url: '/api/v1/status/stream';
};

export type StreamStatusErrors = {
    /**
     * Unexpected server error
     */
    500: ApiError;
};

export type StreamStatusError = StreamStatusErrors[keyof StreamStatusErrors];

export type StreamStatusResponses = {
    /**
     * Server-sent events named status. Each data payload is a status map keyed by service id.
     */
    200: string;
};

export type StreamStatusResponse = StreamStatusResponses[keyof StreamStatusResponses];

export type GetServiceIconData = {
    body?: never;
    path: {
        /**
         * Service identifier.
         */
        serviceId: number;
    };
    query?: never;
    url: '/api/v1/services/{serviceId}/icon';
};

export type GetServiceIconErrors = {
    /**
     * Resource not found
     */
    404: ApiError;
    /**
     * HTTP method is not allowed for this resource
     */
    405: ApiError;
    /**
     * Unexpected server error
     */
    500: ApiError;
};

export type GetServiceIconError = GetServiceIconErrors[keyof GetServiceIconErrors];

export type GetServiceIconResponses = {
    /**
     * Icon image or generated fallback SVG
     */
    200: Blob | File;
};

export type GetServiceIconResponse = GetServiceIconResponses[keyof GetServiceIconResponses];
